### ISSUE TITLE
Question for installing on multiple MATLAB 

### ISSUE THREAD

**Issue by yg-smile** [mathworks-ref-arch/matlab-apache-spark#2]
Dear Authors,

I have multiple versions of MATLAB installed on the same machine (2017a, 2019a, 2020a, 2022a). I was wondering may I install the matlab-apache-spark multiple times, one for each of the versions?
That is, perform the following steps for every version:
1. `buildMatlabSparkUtility`
2. `generateJavapathForSpark()`
3. copy the `javaclasspath.txt` file to the respective `prefdir`

Thank you!

**Comment by asollander** [comment]
Hello,

it should be sufficient that you have one version installed. All MATLAB releases should be able to use it. All MATLAB versions, evidently, should have the correct paths set (Software/MATLAB/startup.m), but there's no need to rebuild the Java libraries.

You will also need the javaclasspath.txt in each prefdir. These can also refer to different Jars, in case you're using several Spark versions.

There is also a config file stored in the `prefdir`, `matlab_spark_config.json`. There should also be copies of this in all releases.

Please note that this package is only officially supported starting with R2019a.

Hth,
Anders

**Comment by yg-smile** [comment]
Thank you for your answer. Have a nice day!
